version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/python:3.7
    resource_class: large
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run: 
          name: Starting docker
          command: sudo docker info

      - run:
          name: Clone Git repository
          command: git clone https://github.com/Netflix/conductor.git

      - run:
          name: Build Conductor Server Docker Image
          command: |
            cd conductor
            cd docker
            sudo docker-compose -f docker-compose.yaml -f docker-compose-postgres.yaml build
      
      - run:
          name: Push Conductor Server Docker Image
          command: |
            echo "Ankit@123docker" | sudo docker login -u "ankit@fynarfin.io" --password-stdin
            sudo docker push anover/conductor:server
            
      - run:
          name: Push Conductor UI Docker Image
          command: |
            echo "Ankit@123docker" | sudo docker login -u "ankit@fynarfin.io" --password-stdin
            sudo docker push anover/conductor:ui

workflows:
  version: 2
  build:
    jobs:
      - build-and-push:
          context: your_docker:hub_context
