version: 2.1

jobs:
  build-and-push:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout

      - run:
          name: Clone Git repository
          command: git clone https://github.com/Netflix/conductor.git

      - run:
          name: Build Conductor Server Docker Image
          command: |
            cd conductor
            cd docker
            docker-compose -f docker-compose.yaml -f docker-compose-postgres.yaml build
      
      - run:
          name: Push Conductor Server Docker Image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push anover/conductor-server
            
      - run:
          name: Push Conductor UI Docker Image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push anover/conductor-ui

workflows:
  version: 2
  build:
    jobs:
      - build-and-push:
          context: your_docker:hub_context
